server:
  port: 9411

spring:
  application:
    name: zipkin-server

  cloud:
    config:
      uri: http://localhost:8888

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"